# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Codetoil.CurvedSpacetimePreview
PackageVersion: 0.1.0-build.96
ManifestType: installer
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/Codetoil/curved-spacetime/releases/download/0.1.0-build.96/curved-spacetime-closed-world-native-variant-windows-x64-0.1.0-build.96.zip
    InstallerSha256: B89D9DC28EB5298AC47E9576CBEBC4F5946C54F426FB9E7A68A4320AFAEFC54F
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: ./curved-spacetime-0.1.0-SNAPSHOT-windows-x64.exe
ManifestVersion: 1.10.0
