# Maven Central - https://repo1.maven.org/maven2/
# org.lwjgl:lwjgl, org.lwjgl:lwjgl-glfw, org.lwjgl:lwjgl-vulkan
lwjglVersion=3.4.1
# Maven Central - https://repo1.maven.org/maven2/
# org.junit:junit-bom
junitVersion=6.1.1
# FabricMC Maven - https://maven.fabricmc.net/
# net.fabricmc:sponge-mixin
fabricMixinVersion=0.17.3+mixin.0.8.7
# QuiltMC Maven - https://maven.quiltmc.org/repository/release/
# org.quiltmc:quilt-loader, org.quiltmc:quilt-loader-dependencies
quiltLoaderVersion=0.30.0-beta.8