# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Codetoil.CurvedSpacetimePreview
PackageVersion: 0.1.0-build.82
ManifestType: installer
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/Codetoil/curved-spacetime/releases/download/0.1.0-build.82/curved-spacetime-closed-world-native-variant-windows-x64-0.1.0-build.82.zip
    InstallerSha256: 02FA85876DC3C64D73F82C1EF0215FDE1D209DB0F8E74357AC33797F7864EB47
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: ./curved-spacetime-0.1.0-SNAPSHOT-windows-x64.exe
ManifestVersion: 1.10.0
