# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Codetoil.CurvedSpacetimePreview
PackageVersion: 0.1.0-build.75
ManifestType: installer
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/Codetoil/curved-spacetime/releases/download/0.1.0-build.75/curved-spacetime-closed-world-native-variant-windows-x64-0.1.0-build.75.zip
    InstallerSha256: 15033D2C46172528CB345651DFE1665E4AA12891B9D892560AF4EC298CA0E617
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: ./curved-spacetime-0.1.0-SNAPSHOT-windows-x64.exe
ManifestVersion: 1.10.0
