# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Codetoil.CurvedSpacetimePreview
PackageVersion: 0.1.0-build.91
ManifestType: installer
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/Codetoil/curved-spacetime/releases/download/0.1.0-build.91/curved-spacetime-closed-world-native-variant-windows-x64-0.1.0-build.91.zip
    InstallerSha256: 8CA86EC2EB63F4D7DD9EED7443B28279BC638691AF790FC667A88A595101D852
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: ./curved-spacetime-0.1.0-SNAPSHOT-windows-x64.exe
ManifestVersion: 1.10.0
