# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Codetoil.CurvedSpacetimePreview
PackageVersion: 0.1.0-build.79
ManifestType: installer
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/Codetoil/curved-spacetime/releases/download/0.1.0-build.79/curved-spacetime-closed-world-native-variant-windows-x64-0.1.0-build.79.zip
    InstallerSha256: AC29709F463AD1D4A594A1D2DB469AC031DCF82453158C4B2E94740FEA8B43D9
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: ./curved-spacetime-0.1.0-SNAPSHOT-windows-x64.exe
ManifestVersion: 1.10.0
