name: Deploy

on:
  push:
    branches:
      - pages
  workflow_run:
    types:
      - completed
    workflows:
      - Gradle Publish
  workflow_dispatch:

permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-to-github-pages:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: pages
      - run: mvn -s maven-settings.xml -Dmaven.repo.local=${{ github.workspace }}/maven/ install
        continue-on-error: true
        env:
          CURVED_SPACETIME_GHA_PAT: ${{ secrets.CURVED_SPACETIME_GHA_PAT }}
      - name: Preform Update
        run: |
          git add .
          git config --global user.name 'Codetoil'
          git config --global user.email 'codetoil@users.noreply.github.com'
          git commit -am "Automated maven update"
          git push