name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '45 15 * * 3'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Run Qodana
        run: ./gradlew qodanaScan
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
